service:
  111814:
    order: "111814"
    service_name: "Click4FunGame"
    password: "U8ZhvXhQq6bGnK4"
    merchant: "221336"
    content_url: "http://www.c4fungames.com"
    lp_url: "http://www.c4fungames.com/dm/pl/lp"
    server_api_url: "https://services.dimoco.at/smart/payment"
    enduser_transport_api_url: "https://services.dimoco.at/smart/userpayment"
    secret: "U8ZhvXhQq6bGnK4"
    notification_url: "http://pl.leadernet-hk.com/notification"
    identify_sub_url_return: "http://pl.leadernet-hk.com/identify/return"
    identify_unsub_url_return: "http://pl.leadernet-hk.com/unsub/identify"
    start_subscription_url_return: "http://pl.leadernet-hk.com/start-sub/return"
    prompt_product_args: "{\"pic\":{\"img\":\"http://www.c4fungames.com/static/img/bg.png\",\"alt\":\"HK Leader\"},\"desc\":{\"pl\":\"Click4Fun GAMES\"}}"
    prompt_merchant_args: "{\"logo\":{\"img\":\"http://pl.leadernet-hk.com/static/img/logo.png\",\"alt\":\"HK Leader\"}}"
    amount: "12.30"
    close_subscription_url_return: "http://pl.leadernet-hk.com/unsub/return"
    welcome_page_url: "http://www.c4fungames.com/dm/pl/welcome"
    unsub_result_url: "http://www.c4fungames.com/unsub/result"
  112278:
    order: "112278"
    service_name: "UncleFunny"
    password: "U8ZhvXhQq6bGnK4"
    merchant: "221336"
    content_url: "http://pl.uncfunny.com"
    lp_url: "http://pl.uncfunny.com/dm/pl/lp"
    server_api_url: "https://services.dimoco.at/smart/payment"
    enduser_transport_api_url: "https://services.dimoco.at/smart/userpayment"
    secret: "U8ZhvXhQq6bGnK4"
    notification_url: "http://pl.leadernet-hk.com/notification"
    identify_sub_url_return: "http://pl.leadernet-hk.com/identify/return"
    identify_unsub_url_return: "http://pl.leadernet-hk.com/unsub/identify"
    start_subscription_url_return: "http://pl.leadernet-hk.com/start-sub/return"
    prompt_product_args: "{\"pic\":{\"img\":\"http://pl.uncfunny.com/static/img/bg.png\",\"alt\":\"HK Leader\"},\"desc\":{\"pl\":\"UncleFunny\"}}"
    prompt_merchant_args: "{\"logo\":{\"img\":\"http://pl.uncfunny.com/static/img/logo.png\",\"alt\":\"HK Leader\"}}"
    amount: "12.30"
    close_subscription_url_return: "http://pl.leadernet-hk.com/unsub/return"
    welcome_page_url: "http://pl.uncfunny.com/dm/pl/welcome"
    unsub_result_url: "http://pl.uncfunny.com/unsub/result"
  112279:
    order: "112279"
    service_name: "MakeULove"
    password: "U8ZhvXhQq6bGnK4"
    merchant: "221336"
    content_url: "http://pl.makeulove.com"
    lp_url: "http://pl.makeulove.com/dm/pl/lp"
    server_api_url: "https://services.dimoco.at/smart/payment"
    enduser_transport_api_url: "https://services.dimoco.at/smart/userpayment"
    secret: "U8ZhvXhQq6bGnK4"
    notification_url: "http://pl.leadernet-hk.com/notification"
    identify_sub_url_return: "http://pl.leadernet-hk.com/identify/return"
    identify_unsub_url_return: "http://pl.leadernet-hk.com/unsub/identify"
    start_subscription_url_return: "http://pl.leadernet-hk.com/start-sub/return"
    prompt_product_args: "{\"pic\":{\"img\":\"http://pl.makeulove.com/static/img/bg.jpg\",\"alt\":\"HK Leader\"},\"desc\":{\"pl\":\"MakeULove\"}}"
    prompt_merchant_args: "{\"logo\":{\"img\":\"http://pl.makeulove.com/static/pornhub/img/logo_bak.png\",\"alt\":\"HK Leader\"}}"
    amount: "12.30"
    close_subscription_url_return: "http://pl.leadernet-hk.com/unsub/return"
    welcome_page_url: "http://pl.makeulove.com/dm/pl/welcome"
    unsub_result_url: "http://pl.makeulove.com/unsub/result"
  112280:
    order: "112280"
    service_name: "PINKCITY"
    password: "U8ZhvXhQq6bGnK4"
    merchant: "221336"
    content_url: "http://pl.pinklycity.com"
    lp_url: "http://pl.pinklycity.com/dm/pl/lp"
    server_api_url: "https://services.dimoco.at/smart/payment"
    enduser_transport_api_url: "https://services.dimoco.at/smart/userpayment"
    secret: "U8ZhvXhQq6bGnK4"
    notification_url: "http://pl.leadernet-hk.com/notification"
    identify_sub_url_return: "http://pl.leadernet-hk.com/identify/return"
    identify_unsub_url_return: "http://pl.leadernet-hk.com/unsub/identify"
    start_subscription_url_return: "http://pl.leadernet-hk.com/start-sub/return"
    prompt_product_args: "{\"pic\":{\"img\":\"http://pl.pinklycity.com/static/img/banner.png\",\"alt\":\"HK Leader\"},\"desc\":{\"pl\":\"PINKCITY\"}}"
    prompt_merchant_args: "{\"logo\":{\"img\":\"http://pl.pinklycity.com/static/img/logo.png\",\"alt\":\"HK Leader\"}}"
    amount: "12.30"
    close_subscription_url_return: "http://pl.leadernet-hk.com/unsub/return"
    welcome_page_url: "http://pl.pinklycity.com/dm/pl/welcome"
    unsub_result_url: "http://pl.pinklycity.com/unsub/result"
